version: '3.8'

services:
  caddy:
    image: caddy:2.8-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
    volumes:
      - svc_1_caddy_svc_data:/data
      - svc_1_caddy_svc_config:/config
      - svc_1_caddy_svc_infra_backups:/infra/backups
      - ./resources/support/caddy/start.sh:/start.sh

  postgres:
    image: bitnami/postgresql:16
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRESQL_USERNAME: infra_sh
      POSTGRESQL_PASSWORD: infra_sh
      POSTGRESQL_DATABASE: infra_sh
    volumes:
      - svc_2_infra_pg_data:/bitnami/postgresql
      - svc_2_infra_pg_infra_backups:/infra/backups

  ptah-app:
    #image: ghcr.io/ptah-sh/ptah-server:latest
    build:
        context: .
        dockerfile: Dockerfile
        
    environment:
      APP_ENV: production
      APP_KEY: base64:APP_KEY
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: infra_sh
      DB_USERNAME: infra_sh
      DB_PASSWORD: infra_sh
      LOG_CHANNEL: errorlog
      APP_URL: localhost
    depends_on:
      - postgres

  ptah-schedule:
    #image: ghcr.io/ptah-sh/ptah-server:latest
    build:
        context: .
        dockerfile: Dockerfile
        
    restart: always
    command: ["sh", "-c", "php artisan config:cache && php artisan schedule:work"]
    environment:
      APP_ENV: production
      APP_KEY: base64:APP_KEY
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: infra_sh
      DB_USERNAME: infra_sh
      DB_PASSWORD: infra_sh
      LOG_CHANNEL: errorlog
      APP_URL: localhost
    depends_on:
      - postgres

  ptah-queue:
    #image: ghcr.io/ptah-sh/ptah-server:latest
    build:
        context: .
        dockerfile: Dockerfile
        
    restart: always
    command: ["sh", "-c", "php artisan config:cache && php artisan queue:work"]
    environment:
      APP_ENV: production
      APP_KEY: base64:APP_KEY
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: infra_sh
      DB_USERNAME: infra_sh
      DB_PASSWORD: infra_sh
      LOG_CHANNEL: errorlog
      APP_URL: localhost
    depends_on:
      - postgres

volumes:
  svc_1_caddy_svc_data:
  svc_1_caddy_svc_config:
  svc_1_caddy_svc_infra_backups:
  svc_2_infra_pg_data:
  svc_2_infra_pg_infra_backups:
